### ISSUE TITLE
Add user to roster

### ISSUE THREAD

**Issue by ricco386** [erigones/Ludolph#20]
Add ability to tell Ludolph to add user to his roster list. Only admin should be able to add users.

**Comment by ricco386** [comment]
Current state of [user subscription management](https://github.com/erigones/Ludolph/wiki/User-subscription-management) has been described in wiki.

This bug will update the functionality and add ability to manage JIDs not from config file but from the roster. What needs to be done:
* Add ability to deny user 'subscribe' request by default (new config option)
* Update command wrapper not check USERS list, but check if user is in roster instead
* Add command to add JID to roster

Possible scenarios after implementation:
* auto_authorize = True, users list is empty: All users can 'subscribe'
* auto_authorize = True, users list is defined: Only users from list can 'subscribe'
* auto_authorize = False, users list is empty: No users can 'subscribe'
* auto_authorize = False, users list is defined: No users can 'subscribe'

This is initial concept of the change... Main benefit is to maintain user roster from Ludolph instead of config (eg. admn doesnt have to have ssh access to server), and adding new users wont require to restart the bot. The question is isnt security risk to trust the server roster, rather than local config file?

**Comment by ricco386** [comment]
User management should use persistent DB to store users that could be in roster.

Have look at XEP-0133: Service Administration and possibly implement when admin add uer to server can be added to ludolph's roster...

**Comment by dn0** [comment]
It turns out that the current user management (via the config file) is sufficient for most of the use cases. Please re-open this issue with a real-life use case.
