### ISSUE TITLE
Zabbix plugin and graph support

### ISSUE THREAD

**Issue by xen0l** [erigones/Ludolph#21]
Zabbix plugin should support obtaining graphs via Zabbix API. It should have the following synopsis:

graph <keyword> <hostgroup/host> [@period]

keyword is a regular expression or pattern, which matches the graph for specific host/hostgroup. 
period represents time period, e.g 1h will show data for the last hour.

Some interesting URLs:
https://www.zabbix.com/documentation/2.2/manual/api/reference/graph/get
https://github.com/sorah/hubot-zabbix/blob/master/scripts/hubot-zabbix.coffee

**Comment by ricco386** [comment]
We have separated zabbix into its own plugin. This bug was re-created there https://github.com/erigones/ludolph-zabbix/issues/1 no need for it to be in core, there fore I am closing it here.
