### ISSUE TITLE
Case sensitive commands

### ISSUE THREAD

**Issue by ricco386** [erigones/Ludolph#40]
Currently commands are case sensitive, but on android mobile clients by default starts with capital letter which results in Ludolph not recognizing the command.

I think to improve UX commands should not be case sensitive: 
* to have 2 commands with same name is confusing
* always press shift before command type on mobile is annoying

**Comment by Pytlicek** [comment]
+1 for this feature. On iOS (Hangouts) app, typing starts always with capital letter.
Maybe simple lower() on input will help ? :)
Thanks

**Comment by dn0** [comment]
Fixed in master

**Comment by Pytlicek** [comment]
I tested it now. It works great ! Thanks for quick fix.
