### ISSUE TITLE
Remind command does not list scheduled jobs

### ISSUE THREAD

**Issue by ricco386** [erigones/Ludolph#65]
I have setup an standard reminder, that works and also executes fine. However when trying to list existing reminders it doesnt works:

```
(10:47:46) Richard: remind add +1 test
(10:47:46) dunajko:  Scheduled job ID 2 scheduled at 2017-02-15T10:48:00 
(10:47:54) Richard: remind
(10:47:54) dunajko:  0 jobs are scheduled 
```

**Comment by dn0** [comment]
This was broken by commit ea7416e (switching remind command from message to attention)
